# Generated by Django 3.0.5 on 2020-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutabakat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
