# Generated by Django 3.0.5 on 2020-05-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutabakat', '0002_auto_20200416_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mutabakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('cari_unvan', models.CharField(max_length=300)),
                ('vergi_kimlik_no', models.CharField(max_length=11)),
                ('ulke_kodu', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('bs_belge_sayisi', models.IntegerField()),
                ('bs_toplam_tutar', models.FloatField()),
                ('ba_belge_sayisi', models.IntegerField()),
                ('ba_toplam_tutar', models.FloatField()),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutabakat.Donem')),
            ],
        ),
    ]
