# Generated by Django 3.0.5 on 2020-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutabakat', '0003_donem_mutabakat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mikroUserId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
